In [ ]:
#numpy party 2
#numerical python

In [8]:
import numpy as np
a = np.array([1,2,3,4,5])
print(a[2] + a[4])

8


#datatypes
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

In [10]:
import numpy as np
a  = np.array(['apple','mango','orange'])
print(a.dtype)

<U6


In [14]:
import numpy as np
a  = np.array([1.2,2.56,3.38,4])
b = a.astype('i')
print(b)
print(b.dtype)


[1 2 3 4]
int32


In [16]:
#cop and view numpy
import numpy as np 
a = np.array([1,2,3,4,5])
x = a.copy()

a[0] = 32

print(a)
print(x)

[32  2  3  4  5]
[1 2 3 4 5]


In [17]:
import numpy as np 
a = np.array([1,2,3,4,5])
x = a.view()

a[0] = 32

print(a)
print(x)

[32  2  3  4  5]
[32  2  3  4  5]


In [ ]:
#numpy part 3
#array sort

In [25]:
import numpy as np 
a = np.array([True,False,True])
print(np.sort(a))


[False  True  True]


In [26]:
#filter
import numpy as np 
a = np.array([2,5,9,4,7])
x = a[[True,False,False,True,False]]
print(x)

[2 4]


In [48]:
#random number
from numpy import random
a = random.choice([3,7,8,4,5])
print(a)

7


In [51]:
#data distribution
from numpy import random
a = random.choice([5,6,4,8], p = [0.2,0.2,0.4,0.2], size=100)
print(a)

[4 4 4 5 5 6 4 8 8 6 8 5 5 4 4 8 6 5 4 8 5 4 5 5 6 4 8 4 6 4 6 4 4 4 4 6 4
 6 6 5 6 4 5 5 6 5 5 4 4 4 4 5 6 5 6 8 8 4 5 8 6 6 6 8 4 4 8 8 5 5 6 4 4 4
 4 6 4 4 4 6 4 4 6 8 4 4 4 5 5 6 4 5 5 4 4 4 8 8 5 6]
